### ISSUE TITLE
只想修改config.yaml，同时保留geoip.dat，geosite.dat随镜像更新。

### ISSUE THREAD

**Issue by mjyhj** [Sagit-chu/mosdns-container#13]
问一下
如果只想修改config.yaml，同时保留geoip.dat，geosite.dat随镜像更新。
该怎么挂载

**Comment by Sagit-chu** [comment]
暂时没这个功能，要么就全挂载要么就全不挂

**Comment by mjyhj** [comment]
> 暂时没这个功能，要么就全挂载要么就全不挂

那建议把entrypoint.sh修改一下，无论挂不挂载配置文件，都随镜像用最新的geosite.dat和geoip.dat

`#!/bin/sh
if [ ! -f /etc/mosdns/config.yaml ]; then
	mkdir -p /etc/mosdns/
	cp -u /config.yaml /etc/mosdns/config.yaml
fi
cp -u /geosite.dat /etc/mosdns/geosite.dat
cp -u /geoip.dat /etc/mosdns/geoip.dat
/usr/bin/mosdns start --dir /etc/mosdns`

**Comment by Sagit-chu** [comment]
> > 暂时没这个功能，要么就全挂载要么就全不挂
> 
> 那建议把entrypoint.sh修改一下，无论挂不挂载配置文件，都随镜像用最新的geosite.dat和geoip.dat
> 
> #!/bin/sh if [ ! -f /etc/mosdns/config.yaml ]; then mkdir -p /etc/mosdns/ cp -u /config.yaml /etc/mosdns/config.yaml fi cp -u /geosite.dat /etc/mosdns/geosite.dat cp -u /geoip.dat /etc/mosdns/geoip.dat /usr/bin/mosdns start --dir /etc/mosdns

提交PR啊😂😂你都写了不提pr
