### ISSUE TITLE
The upstream version has been bumped to 5.0.0

### ISSUE THREAD

**Issue by wu2305** [Sagit-chu/mosdns-container#19]
There have been several changes in the mosdns and the format of the config files.

1. The parser of geoip.dat and geosite.dat has been removed from mosdns 5.0.0
2. The listener became a brand-new plugin of mosdns.
3. The function of sequence plugin became much more complex.

Before switching to mosdns v5, there are several tasks to be complete:

1. The domain_list of [CN](https://raw.githubusercontent.com/QiuSimons/Chnroute/master/dist/chnroute/chinalist.txt) and [Ads](https://raw.githubusercontent.com/sjhgvr/oisd/main/dbl_full.txt)
2. The ip_addr_list of the [ip addresses in CN](https://raw.githubusercontent.com/misakaio/chnroutes2/chnroutes.txt)
3. The available config file

**Comment by wu2305** [comment]
Further more, the TCP connection towards Google Public DNS is blocked in several environments.
It's time to use cloudflare public dns as alternative

**Comment by Sagit-chu** [comment]
fixed [cc8588d](https://github.com/Sagit-chu/mosdns-container/commit/cc8588d22382a8a0e659d8bc8860162539c908e7)
