### ISSUE TITLE
默认配置dns有点问题

### ISSUE THREAD

**Issue by warrenhoo** [Sagit-chu/mosdns-container#22]
默认配置dns有点问题，可能与我ping1.1.1.1 ping不通有问题，ping 1.0.0.1是可以Ping通的。所以我在upstreaml里加了一个coudflare tls://1.0.0.1和一个google的tls://8.8.8.8
修改后被墙域名是可以访问了，但是还有一些错误，比如
WARN upstreams upstream error {"uqid": 1129, "qname": "auth.docker.io.", "qtype": 1, "qclass": 1, "upstream": "google", "error": "context deadline exceeded"}
WARN upstreams upstream error {"uqid": 1131, "qname": "api.github.com.", "qtype": 1, "qclass": 1, "upstream": "google", "error": "context deadline exceeded"}

context deadline exceeded是个什么意思？

**Comment by Sagit-chu** [comment]
这应该是上游的bug。。在 2023年3月26日，00:20，warren ***@***.***> 写道：﻿
默认配置dns有点问题，可能与我ping1.1.1.1 ping不通有问题，ping 1.0.0.1是可以Ping通的。所以我在upstreaml里加了一个coudflare tls://1.0.0.1和一个google的tls://8.8.8.8
修改后被墙域名是可以访问了，但是还有一些错误，比如
WARN upstreams upstream error {"uqid": 1129, "qname": "auth.docker.io.", "qtype": 1, "qclass": 1, "upstream": "google", "error": "context deadline exceeded"}
WARN upstreams upstream error {"uqid": 1131, "qname": "api.github.com.", "qtype": 1, "qclass": 1, "upstream": "google", "error": "context deadline exceeded"}
context deadline exceeded是个什么意思？

**Comment by warrenhoo** [comment]
希望默认配制能将国外去dns配制成1.0.0.1和8.8.8.8

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 1072776884** [comment]
tls是不是老被运营商阻断，用doh会不会好点

**Comment by Sagit-chu** [comment]
> tls是不是老被运营商阻断，用doh会不会好点

国外的应该直接走科学去了 不应该被阻断吧。。
